version: '{build}'

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#
platform: Any CPU
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    COMPILER: mingw
    TOOLSET: w64-mingw32
    ARCH: x86_64
    GENERATOR: '"MinGW Makefiles"'
    MINGW_DIR_BIN: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
    CMAKE_C_COMPILER: C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/gcc.exe
    CMAKE_CXX_COMPILER: C:/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/g++.exe
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc15
    ARCH: win32
    GENERATOR: '"Visual Studio 15 2017"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc15
    ARCH: win64
    GENERATOR: '"Visual Studio 15 2017 Win64"'

#---------------------------------#
#            steps                #
#---------------------------------#
install:
  - cmd: git submodule update --init
  - cmd: mkdir build
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=%MINGW_DIR_BIN%;%PATH%
  - cmd: cd build & cmake .. -G %GENERATOR% -DWRENBIND17_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=MinSizeRel || exit 1 & cd ..

build_script:
  - cmd: cd build & cmake --build . --config "MinSizeRel" || exit 1 & cd ..

test_script:
  - cmd: cd build & ctest --verbose -C "MinSizeRel" || exit 1 & cd ..

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  - provider: Email
    to:
      - matusnov@gmail.com
    on_build_success: true
    on_build_failure: true
    