version: 2
jobs:
  pages:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      
      - run:
          name: Dependencies
          command: |
            sudo apt-get install doxygen zip unzip -y
            wget https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_extended_0.59.1_Linux-64bit.deb
            sudo dpkg -i hugo_extended_0.59.1_Linux-64bit.deb
            wget https://github.com/matusnovak/doxybook2/releases/download/v1.0.0/doxybook2-linux-amd64-v1.0.0.zip
            unzip doxybook2-linux-amd64-v1.0.0.zip
            sudo cp bin/doxybook2 /usr/local/bin/doxybook2
            sudo chmod +x /usr/local/bin/doxybook2

      - run:
          name: Generate documentation
          command: |
            doxygen
            doxybook2 \
              --input temp/xml \
              --output docs/content \
              --config docs/.doxybook/config.json \
              --templates docs/.doxybook/templates
            rm -rf docs/content/Examples
            rm -rf docs/content/Pages
      
      - run:
          name: Build static pages
          command: |
            cd docs
            hugo
            cp -rv ./public /tmp/public
              
      - persist_to_workspace:
          root: /tmp
          paths:
            - public

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "72:4f:5d:f5:3f:24:82:ec:28:72:1f:26:91:03:47:68"

      - attach_workspace:
          at: /tmp

      - run:
          name: Dependencies
          command: |
            sudo npm install -g gh-pages@2.0.1

      - run:
          name: Deploy
          command: |
            cp -rv /tmp/public ./public
            git config --global user.email "$GITHUB_USER_EMAIL"
            git config --global user.name "$GITHUB_USER_NAME"
            gh-pages --dist ./public

workflows:
  version: 2
  build_and_test:
    jobs:
      - pages
#          filters:
#            branches:
#              only:
#                - master
      - deploy:
          requires:
            - pages
#          filters:
#            branches:
#              only:
#                - master
